on:
    push:
        branches-ignore:
            - master
            - version-*
#     paths:
#    - gradle.properties
#    - package_info.json

jobs:
    build-job:
        uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
        with:
            build-target: 'Docker'
            docker-username: ${{ github.actor }}
        secrets:
            docker-password: ${{ secrets.GITHUB_TOKEN }}